Repository assawti/SwiftBuy, pull requests merged in 2025-02, with the labels that each got.

#3 payment method added
  payment.md
Labels: documentation

#1 added my info and plan overview
  index.html
  myinfo.md
Labels: enhancement

#2 update to feature
  deliveryupdate.md
Labels: enhancement

#5 this is my cart
  fred.md
Labels: documentation, enhancement

#6 this is an update to my markdown file
  myinfo.md
Labels: documentation

#7 Develop
  deliveryupdate.md
  fred.md
  index.html
  myinfo.md
  payment.md
Labels: documentation
